innika/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.auth import views as auth_views
from adminfunction.forms import LoginForm
from django.views.generic import TemplateView
from adminfunction import views as admin_view
from location import views as location_view
from page import views as page_view
from faqs import views as faqs_view
from menu import views as menu_view
from testimonial import views as testimonial_view
from properties import views as properties_view
from frontend import views as frontend_view
from contactus import views as contactus_view
from makeenquery import views as makeenquery_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    #Admin URL
    path('dj-admin',admin_view.admin_login,name='adminlogin'),
    path('admin/dashboard',admin_view.dashboard,name='dashboard'),
    path('logout',admin_view.handlelogout),
    path('admin/addlocation',location_view.addlocation,name='addlocation'),
    path('admin/location',location_view.location,name='location'),
    path('admin/deletelocation/<int:locationid>',location_view.deletelocation),
    path('admin/editlocation/<int:locationid>',location_view.editlocation),
    path('admin/page',page_view.page,name='page'),
    path('admin/addpage',page_view.addpage,name='addpage'),
    path('admin/editpage/<int:pageid>',page_view.editpage,name='editpage'),
    path('admin/deletepage/<int:pageid>',page_view.addpage,name='deletepage'),
    path('admin/faqs/add',faqs_view.addfaqs,name='addfaqs'),
    path('admin/faqs/edit/<int:faqsid>',faqs_view.editfaqs,name='editfaqs'),
    path('admin/faqs',faqs_view.faqs,name='adminfaqs'),
    path('admin/faqs/delete/<int:faqsid>',faqs_view.deletefaqs,name='deletefaqs'),
    path('admin/testimonial/add',testimonial_view.add,name='addtestimonial'),
    path('admin/testimonial',testimonial_view.index,name='admintestimonial'),
    path('admin/testimonial/edit/<int:testimonialid>',testimonial_view.edit,name='edittestimonial'),
    path('admin/testimonial/delete/<int:testimonialid>',testimonial_view.delete,name='deletetestimonial'),
    path('admin/change-password/',admin_view.PasswordChangeView.as_view(template_name='admintemplates/change-password.html'),name='change_password'),
    path('admin/user-profile/',admin_view.PasswordChangeView.as_view(template_name='admintemplates/user-profile.html'),name='user_profile'),
    path('admin/properties',properties_view.index,name='adminproperties'),
    path('admin/properties/edit/<int:propertiesid>',properties_view.edit,name='editproperties'),
    path('admin/properties/create',properties_view.create,name='createproperties'),
    path('admin/properties/delete/<int:propertiesid>',properties_view.delete,name='deleteimageproperties'),
    path('admin/properties/deleteproperties/<int:propertiesid>',properties_view.deleteproperties,name='deleteproperties'),
    path('admin/properties/deleteproperties/<int:propertiesid>',properties_view.deleteproperties,name='deleteproperties'),
    path('admin/menu',menu_view.menu,name='menu'),
    path('admin/contactus',contactus_view.index,name='contactus'),
    path('admin/enquery',makeenquery_view.index,name='enquery'),
    path('ckeditor',include('ckeditor_uploader.urls')),
    #Frontend URL
    path('',frontend_view.home,name='home'),
    path('page/<str:pageslug>',frontend_view.index,name='index'),
    path('location/',frontend_view.location,name='location1'),
    path('properties/',frontend_view.properties,name='properties'),
    path('propertiesdetails/<str:slug>/',frontend_view.property_details,name='propertiesdetails'),
    path('testimonial',frontend_view.testimonial,name='testimonial'),
    path('faqs',frontend_view.faqs,name='faqs'),
    path('addcontactus',contactus_view.contactuspost),
    path('addcontactus',contactus_view.contactuspost),
    path('enquery',frontend_view.makeenquery,name='makeenquery'),
    path('addenquery',makeenquery_view.addmakeenquery,name='addmakeenquery'),
# )
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faqs/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Faqs(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextField(blank=True,null=True)

    def __str__(self):
        return self.name

menu/models.py
from django.db import models

# Create your models here.
# Create your models here.
class Menu(models.Model):
    menu_id = models.IntegerField()
    name = models.CharField(max_length=70)
    slug = models.CharField(max_length=70,null=True)
    parent_id = models.IntegerField()
    
    def __str__(self):
        return self.name

faqs/forms.py
from django import forms
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget
from .models import Faqs

class FaqsForm(forms.ModelForm):
     class Meta:
        # specify model to be used
        model = Faqs
        fields = '__all__'
        labels ={
            'title':'Accordion Title',
            'content':'Accordion Description',
        }
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            
        }

faqs/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from adminfunction.middleware.auth import auth_middleware
from .forms import FaqsForm
from .models import Faqs
# Create your views here.
@auth_middleware
def faqs(request):
    loc = Faqs.objects.all()
    return render(request,'admintemplates/faqs/index.html',{'location':loc})

@auth_middleware
def addfaqs(request):
    if request.method == 'POST':
        fn = FaqsForm(request.POST)  
        if fn.is_valid():
            accoradation_title = fn.cleaned_data['title']
            accoradation_desc = fn.cleaned_data['content']
            en = Faqs(title=accoradation_title,content=accoradation_desc)
            en.save()
            return redirect('/admin/faqs')
        # else:
            # return render(request, 'admintemplates/addlocation.html', {'form':fn})
    else:
        fn=FaqsForm()
    return render(request,'admintemplates/faqs/add.html',{'form':fn})

def editfaqs(request,faqsid):
    if(request.user.is_authenticated == False):
        return redirect('/dj-admin')
    else:
        pi = Faqs.objects.get(id=faqsid)
        fn=FaqsForm(request.POST or None,instance = pi)
        if request.method == 'POST':
            if fn.is_valid():
                fn.save()
                return redirect('/admin/faqs')
            else:
                return render(request,'admintemplates/faqs/edit.html',{'form':fn})
        else:
            return render(request,'admintemplates/faqs/edit.html',{'form':fn})
        
def deletefaqs(request,faqsid):

    if(request.user.is_authenticated == False):
        return redirect('/dj-admin')
    else:
        location = Faqs.objects.get(id=faqsid)
        location.delete()
        return redirect('/admin/faqs')

templates/admintemplates/faqs/add.html
{% extends 'admintemplates/layout.html' %}
{% block content %}
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Create FAQS</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Create FAQS</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!--end breadcrumb-->
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <div class="card">
                <div class="card-body">
                    <div class="item-content">
                        <div class="mb-3">
                            <label for="test_0_name text-uppercase" class="form-label" for="{{form.title.auto_id}}">{{form.title.label}}</label>
                            {{form.title}}
                            <span class="text-danger">{{form.title.errors}}</span>
                        </div>
                        <div class="mb-3 d-flex flex-column">
                            <label for="test_0_name text-uppercase" class="form-label" for="{{form.content.auto_id}}">{{form.content.label}}</label>
                            {{form.content}}
                            <span class="text-danger">{{form.content.errors}}</span>
                        </div>
                    </div>
                    <div >
                        {{form.media}}
                    </div>
                    <input type="submit" class="btn btn-primary mb-3" value="Add FAQS">    
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
    <script>
        $('#id_title').keyup(function(){    
            let slug = $(this).val();
            $('#id_slug').val(slug.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, ''));
        })
    </script>
	<!-- <script>
		var quill = new Quill('#editor', {
		  theme: 'snow'
		});
	</script> -->
{% endblock %}

templates/admintemplates/faqs/edit.html
{% extends 'admintemplates/layout.html' %}
{% block content %}
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Edit FAQS</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Edit FAQS</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!--end breadcrumb-->
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <div class="card">
                <div class="card-body">
                    <div class="item-content">
                        <div class="mb-3">
                            <label for="test_0_name text-uppercase" class="form-label" for="{{form.title.auto_id}}">{{form.title.label}}</label>
                            {{form.title}}
                            <span class="text-danger">{{form.title.errors}}</span>
                        </div>
                        <div class="mb-3 d-flex flex-column">
                            <label for="test_0_name text-uppercase" class="form-label" for="{{form.content.auto_id}}">{{form.content.label}}</label>
                            {{form.content}}
                            <span class="text-danger">{{form.content.errors}}</span>
                        </div>
                    </div>
                    <div >
                        {{form.media}}
                    </div>
                    <input type="submit" class="btn btn-primary mb-3" value="Update FAQS">    
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
    <script>
        $('#id_title').keyup(function(){    
            let slug = $(this).val();
            $('#id_slug').val(slug.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, ''));
        })
    </script>
	<!-- <script>
		var quill = new Quill('#editor', {
		  theme: 'snow'
		});
	</script> -->
{% endblock %}

templates/admintemplates/faqs/index.html
{% extends 'admintemplates/layout.html' %}
{% block content %}
{% load static %}
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">FAQS</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">FAQS</li>
                    </ol>
                </nav>
            </div>
            <div class="ms-auto">
                <div class="btn-group">
                    <a href="{% url 'addfaqs' %}" class="btn btn-primary">Add FAQS</a>
                    <!-- <button type="button" class="btn btn-primary split-bg-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown">	<span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-end">	<a class="dropdown-item" href="javascript:;">Action</a>
                        <a class="dropdown-item" href="javascript:;">Another action</a>
                        <a class="dropdown-item" href="javascript:;">Something else here</a>
                        <div class="dropdown-divider"></div>	<a class="dropdown-item" href="javascript:;">Separated link</a>
                    </div> -->
                </div>
            </div>
        </div>
        <!--end breadcrumb-->
        <!-- <h6 class="mb-0 text-uppercase">Location</h6>
        <hr/> -->
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Page Name</th>
                                <th></th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for loc in location %}
                            <tr>
                                <td>{{loc.title}}</td>
                                <td>
                                    {% autoescape off %}
                                        {{loc.content}}
                                    {% endautoescape %}
                                </td>
                                <td>
                                    <div class="d-flex w-50">
                                        <a href="/admin/faqs/edit/{{loc.id}}">
                                            <div class="font-22 text-primary"><i class="fadeIn animated bx bx-edit-alt"></i>
                                            </div>
                                        </a>
                                        <form action="/admin/faqs/delete/{{loc.id}}" method="post">
                                            {% csrf_token %}
                                            <button class="p-0 border-0"><div class="font-22 text-danger"><i class="fadeIn animated bx bx-trash"></i>
                                            </div></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th></th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        $('#example').DataTable();
      });
</script>
{% endblock %}